# -*- mode: ruby -*-
# vi: set ft=ruby :

## require https://github.com/oscar-stack/vagrant-hosts

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise64"


  config.vm.boot_timeout = 600
  config.vbguest.auto_update = true

  # configure zookeeper cluster
  (1..1).each do |i|
    config.vm.define "zookeeper#{i}" do |s|
      s.vm.provision "shell", path: "vagrant/scripts/init.sh"
      s.vm.hostname = "zookeeper#{i}.kafkafast"
      s.vm.network :private_network, ip: "192.168.4.#{i+1}"
      s.vm.provision "shell", path: "vagrant/scripts/zookeeper.sh", args:"#{i}"
      s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}
    end
  end

  # configure brokers
  (1..3).each do |i|
    config.vm.define "broker#{i}" do |s|
      s.vm.provision "shell", path: "vagrant/scripts/init.sh"
      s.vm.hostname = "broker#{i}.kafkafast"
      s.vm.network :private_network, ip: "192.168.4.4#{i-1}"
      s.vm.provision "shell", path: "vagrant/scripts/broker.sh", args: "#{i}"
      s.vm.synced_folder "~/.m2", "/home/vagrant/.m2", type: "nfs"

      s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}
    end
  end

  # configure redis
  config.vm.define "services1" do |s|
    s.vm.hostname = "services1.kafkafast"
    s.vm.network  :private_network, ip:  "192.168.4.10"
    #cluster will start redis cluster, any other value will start a single redis
    s.vm.provision "shell", path: "vagrant/scripts/services.sh", args:"cluster"
    s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}
  end

  # configure kerberos
  config.vm.define "kerberos" do |s|
      s.vm.hostname = "kerberos.kafkafast"
      s.vm.network  :private_network, ip:  "192.168.4.60"

      #cluster will start kerberos services
      s.vm.provision "shell", path: "vagrant/scripts/kerberos.sh", args:"cluster"
      s.vm.synced_folder ".", "/vagrant",  :nfs => { :mount_options => ["dmode=777","fmode=777"]}
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end


  ### etc hosts setup see https://github.com/oscar-stack/vagrant-hosts

  config.vm.provision :hosts do |provisioner|
      # Add a single hostname
      provisioner.autoconfigure = true
      provisioner.sync_hosts = true
      provisioner.add_localhost_hostnames = false # do not add FQDN to 127.0.0.1
  end

end

