# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "gerritjvv/centos-6.5-java"

  config.vm.boot_timeout = 600
  config.vbguest.auto_update = true

  config.vm.provision "shell", path: "vagrant/scripts/init.sh"

  # configure zookeeper cluster
  (1..1).each do |i|
    config.vm.define "zookeeper#{i}" do |s|
      s.vm.hostname = "zookeeper#{i}"
      s.vm.network :private_network, ip: "192.168.4.#{i+1}"
      s.vm.provision "shell", path: "vagrant/scripts/zookeeper.sh", args:"#{i}"
    end
  end

  # configure brokers
  (1..3).each do |i|
    config.vm.define "broker#{i}" do |s|
      s.vm.hostname = "broker#{i}"
      s.vm.network :private_network, ip: "192.168.4.4#{i-1}"
      s.vm.provision "shell", path: "vagrant/scripts/broker.sh", args:"#{i}"
    end
  end

  # configure redis
  config.vm.define "services1" do |s|
    s.vm.hostname = "services1"
    s.vm.network  :private_network, ip:  "192.168.4.10"
    s.vm.provision "shell", path: "vagrant/scripts/services.sh"
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end

